id: P010497
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18916
  title: ས་ཞིང་བཤུག་སྤྲོད་དང་ཁང་པ་ཉོ་འཚོང་།
  author: ''
  volumes:
    5977ec96d72c4c5aa82884854636c33b:
      image_group_id: I8LS18918
      title: ''
      volume_number: 1
      total_pages: 346
      base_file: v001.txt
