id: IC97112EC
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-27T10:22:58+00:00'
last_modified: '2022-06-08T14:02:08.314574+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8LS18916
  title: ས་ཞིང་བཤུག་སྤྲོད་དང་ཁང་པ་ཉོ་འཚོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    EDD8:
      image_group_id: I8LS18918
      title: ''
      total_pages: 346
      order: 1
      base_file: EDD8.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
